version: "3"
services:
# Балансировщик 
  nginx-balancer:
    image: nginx:alpine-slim
    restart: always
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/:/var/log/nginx/
    ports:
      - 3000:80
    depends_on:
      - the-name-service

# Сервис
  the-name-service:
    build: 
      context: ../service/TheName
      dockerfile: ./build/Dockerfile
    environment:
      SERVER_PORT: "8080"
      SERVER_HOST: "0.0.0.0"

      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "postgres"      
      DB_SSL: "disable"

      LOG_LEVEL: "debug"

    depends_on: 
      database:
        condition: service_healthy

# База данных
  database:
    image: postgres:alpine
    restart: always
    volumes:
      - ./volumes/database/postgres-data:/var/lib/postgresql/data
      - ../migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:      
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres "]
      interval: 5s
      timeout: 5s
      retries: 5


    