// Package autogen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package autogen

// DeleteHumansParams defines parameters for DeleteHumans.
type DeleteHumansParams struct {
	// Ids Уникальные идентификаторы людей для удаления
	Ids []int `form:"ids" json:"ids"`
}

// GetHumansParams defines parameters for GetHumans.
type GetHumansParams struct {
	// Limit Как много объектов вернуть за один раз
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Выборка с n-ого
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Id Возраст
	Id *int `form:"id,omitempty" json:"id,omitempty"`

	// Name Имя
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Surname фамилия
	Surname *string `form:"surname,omitempty" json:"surname,omitempty"`

	// Patronymic отчество
	Patronymic *string `form:"patronymic,omitempty" json:"patronymic,omitempty"`

	// Age Возраст
	Age *int `form:"age,omitempty" json:"age,omitempty"`

	// Sex Пол человека
	Sex *string `form:"sex,omitempty" json:"sex,omitempty"`

	// Nation нация
	Nation *string `form:"nation,omitempty" json:"nation,omitempty"`

	// SortBy Сортировать по
	SortBy *string `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortScale сортировать по
	SortScale *string `form:"sort_scale,omitempty" json:"sort_scale,omitempty"`
}

// AddHumansJSONBody defines parameters for AddHumans.
type AddHumansJSONBody = []struct {
	// Name Имя
	Name string `json:"name"`

	// Patronymic Отчество, если есит
	Patronymic *string `json:"patronymic,omitempty"`

	// Surname Фамилия
	Surname string `json:"surname"`
}

// UpdateHumansJSONBody defines parameters for UpdateHumans.
type UpdateHumansJSONBody = []struct {
	// Id Уникальный идентификатор
	Id *int `json:"id,omitempty"`

	// Name Имя
	Name string `json:"name"`

	// Patronymic Отчество, если есит
	Patronymic *string `json:"patronymic,omitempty"`

	// Surname Фамилия
	Surname string `json:"surname"`
}

// UpdateHumanJSONBody defines parameters for UpdateHuman.
type UpdateHumanJSONBody struct {
	// Id Уникальный идентификатор
	Id *int `json:"id,omitempty"`

	// Name Имя
	Name string `json:"name"`

	// Patronymic Отчество, если есит
	Patronymic *string `json:"patronymic,omitempty"`

	// Surname Фамилия
	Surname string `json:"surname"`
}

// AddHumansJSONRequestBody defines body for AddHumans for application/json ContentType.
type AddHumansJSONRequestBody = AddHumansJSONBody

// UpdateHumansJSONRequestBody defines body for UpdateHumans for application/json ContentType.
type UpdateHumansJSONRequestBody = UpdateHumansJSONBody

// UpdateHumanJSONRequestBody defines body for UpdateHuman for application/json ContentType.
type UpdateHumanJSONRequestBody UpdateHumanJSONBody
